CREATE TABLE IF NOT EXISTS user_api_sources (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  method VARCHAR(20) NOT NULL DEFAULT 'GET',
  url VARCHAR(500) NOT NULL,
  keyword_param VARCHAR(100) NOT NULL DEFAULT 'q',
  keyword_position VARCHAR(20) NOT NULL DEFAULT 'url_param',
  type_param VARCHAR(100) NULL,
  type_position VARCHAR(20) NULL DEFAULT 'url_param',
  option_delimiter VARCHAR(20) NULL DEFAULT '###',
  option_format VARCHAR(255) NULL,
  headers TEXT NULL,
  extra_config TEXT NULL,
  data_path VARCHAR(255) NULL DEFAULT 'data',
  success_code_field VARCHAR(100) NULL DEFAULT 'code',
  success_code_value VARCHAR(100) NULL DEFAULT '1',
  timeout INT NOT NULL DEFAULT 10,
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(500) NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  INDEX idx_user_status (user_id, status)
);
